# docker compose up -d --build --force-recreate
version: '3.8'
name: infra

services:

  jenkins:
    container_name: jenkins
    build:
      dockerfile_inline: |
        FROM jenkins/jenkins:jdk17
        USER root
        RUN apt-get update && apt-get install -y lsb-release
        RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
          https://download.docker.com/linux/debian/gpg
        RUN echo "deb [arch=$(dpkg --print-architecture) \
          signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
          https://download.docker.com/linux/debian \
          $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
        RUN apt-get update && apt-get install -y docker-ce maven
        RUN usermod -aG docker jenkins
      #  USER jenkins
      # RUN jenkins-plugin-cli --plugins "blueocean docker-workflow"
    ports:
      - 9000:8080
      - 50000:50000
    volumes:
      - $CONFIG/jenkins:/var/jenkins_home
      # for mac distro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - infra

  # sonar:
  #   container_name: sonar
  #   image: sonarqube:latest
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - $CONFIG/sonarqube/data:/opt/sonarqube/data
  #     - $CONFIG/sonarqube/logs:/opt/sonarqube/logs
  #     - $CONFIG/sonarqube/extensions:/opt/sonarqube/extensions
  #   environment:
  #     - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  #   networks:
  #     - infra

  artilleryio:
    container_name: artilleryio
    image: artilleryio/artillery:latest
    # platform: linux/amd64
    volumes:
      - $CONFIG/artilleryio:/artillery
    networks:
      - infra

networks:
  infra:
    driver: bridge